title: Super Cool Website
description: Wow, this is amazing!
theme: just-the-docs
logo: "assets/images/logo.png"

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

callouts:
  note:
    color: blue
  warning:
    title: ⚠️ Warning
    color: red
  tip:
    color: green
