title: WAPHL Test Website
description: This is a test website
theme: just-the-docs
logo: "assets/images/logo.png"
favicon_icon: "assets/images/logo.png"

url: https://just-the-docs.github.io

color_scheme: dark

aux_links:
  This could be a link to anything: https://github.com/just-the-docs/just-the-docs-template

callouts:
  note:
    color: blue
  warning:
    title: ⚠️ Warning
    color: red
  tip:
    color: green

footer_content: "Dang this is cool!"
