title: Super Cool Website
description: Wow, this is amazing!
theme: just-the-docs
logo: "/assets/images/just-the-docs.png"

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
